import type { Product } from "@/components/home/product-card";

export interface StoreProduct extends Product {
  categoryId: string;
  description?: string;
  tags?: string[];
  rating?: number;
  reviewCount?: number;
  origin?: string;
  storage?: string;
  nutritionHighlights?: string[];
}

export const CATEGORIES = [
  { id: "vegetables", label: "Fresh Vegetables", emoji: "🥦", count: 45 },
  { id: "diet",       label: "Diet Foods",       emoji: "🥗", count: 32 },
  { id: "nutrition",  label: "Diet Nutrition",   emoji: "💊", count: 18 },
  { id: "fastfood",   label: "Fast Food Items",  emoji: "🍔", count: 27 },
  { id: "fruits",     label: "Fruits Items",     emoji: "🍉", count: 38 },
  { id: "healthy",    label: "Healthy Foods",    emoji: "🥑", count: 24 },
  { id: "grocery",    label: "Grocery Items",    emoji: "🛒", count: 56 },
  { id: "dairy",      label: "Quality Milk",     emoji: "🥛", count: 19 },
  { id: "drinks",     label: "Cold Drinks",      emoji: "🥤", count: 22 },
  { id: "beef",       label: "Beef Steak",       emoji: "🥩", count: 15 },
  { id: "vitamins",   label: "Vitamin Items",    emoji: "🍋", count: 12 },
  { id: "chicken",    label: "Raw Chicken",      emoji: "🍗", count: 14 },
  { id: "breakfast",  label: "Breakfast Item",   emoji: "🍳", count: 21 },
  { id: "fish",       label: "Fish Items",       emoji: "🐟", count: 16 },
  { id: "greens",     label: "Green Vegetables", emoji: "🥬", count: 28 },
  { id: "snacks",     label: "Cookies & Biscuits", emoji: "🍪", count: 34 },
];

export const ALL_PRODUCTS: StoreProduct[] = [
  // vegetables
  { id: "p1",  name: "Broccoli Crown Large",        price: 2.49, unit: "1 each",  emoji: "🥦", categoryId: "vegetables", rating: 4.7, reviewCount: 128, description: "Crisp, fresh broccoli crown — packed with vitamins C and K. Grown locally and harvested at peak ripeness for maximum flavour and nutrition.", tags: ["Organic", "Local", "Seasonal"], origin: "California, USA", storage: "Refrigerate. Use within 5 days.", nutritionHighlights: ["High Vitamin C", "High Fibre", "Low Calorie"] },
  { id: "p2",  name: "Organic Baby Spinach 150g",   price: 3.29, originalPrice: 3.99, onSale: true, unit: "150g", emoji: "🥬", categoryId: "vegetables", rating: 4.8, reviewCount: 214, description: "Pre-washed tender baby spinach leaves. Ready to eat — perfect for salads, smoothies, and sautés. Certified organic, no pesticides.", tags: ["Organic", "Pre-Washed", "Ready to Eat"], origin: "Mexico", storage: "Keep refrigerated. Best before printed on pack.", nutritionHighlights: ["Iron Rich", "Vitamin K", "Folate"] },
  { id: "p3",  name: "Cherry Tomatoes 250g",        price: 2.99, unit: "250g",    emoji: "🍅", categoryId: "vegetables", rating: 4.6, reviewCount: 97, description: "Sun-ripened cherry tomatoes bursting with natural sweetness. Great for snacking, salads, pasta, and roasting.", tags: ["Vine Ripened", "Sweet"], origin: "Spain", storage: "Store at room temperature. Do not refrigerate.", nutritionHighlights: ["Lycopene", "Vitamin C", "Antioxidants"] },
  { id: "p4",  name: "Carrots 1kg Bag",             price: 1.99, unit: "1kg",     emoji: "🥕", categoryId: "vegetables", rating: 4.5, reviewCount: 183, description: "Sweet, crunchy carrots perfect for snacking, roasting, soups, and juicing. Rich in beta-carotene and natural sugars.", tags: ["High Beta-Carotene", "Versatile"], origin: "Australia", storage: "Refrigerate for up to 3 weeks.", nutritionHighlights: ["Beta-Carotene", "Fibre", "Potassium"] },
  { id: "p5",  name: "Bell Peppers Mixed",          price: 3.00, priceMax: 5.00, unit: "1 each", emoji: "🫑", categoryId: "vegetables", hasVariants: true, rating: 4.4, reviewCount: 76, description: "Vibrant mixed bell peppers — red, yellow, and green. Sweet and crisp with an excellent crunch. Use raw or cook into stir-fries and grills.", tags: ["Colourful", "Rich in Vitamin C"], origin: "Netherlands", storage: "Refrigerate. Use within 1 week.", nutritionHighlights: ["Vitamin C", "Vitamin A", "Antioxidants"] },
  { id: "p6",  name: "Cucumber Long",               price: 1.49, unit: "1 each",  emoji: "🥒", categoryId: "vegetables", rating: 4.3, reviewCount: 55, description: "Cool and refreshing long cucumber. Low in calories and high in water content. Perfect for salads, tzatziki, and snacking.", tags: ["Hydrating", "Low Calorie"], origin: "UK", storage: "Refrigerate after cutting. Best used within 3 days.", nutritionHighlights: ["Hydrating", "Vitamin K", "Low Calorie"] },
  { id: "p7",  name: "Red Onions 1kg",              price: 1.79, unit: "1kg",     emoji: "🧅", categoryId: "vegetables", rating: 4.6, reviewCount: 102, description: "Bold, pungent red onions with a slightly sweet finish when cooked. Indispensable for caramelising, pickling, and raw salads.", tags: ["Aromatic", "Versatile"], origin: "Peru", storage: "Store in a cool, dry, dark place. Up to 1 month.", nutritionHighlights: ["Quercetin", "Fibre", "Antioxidants"] },
  { id: "p8",  name: "Garlic Bulb 3pk",             price: 1.99, unit: "3 pack",  emoji: "🧄", categoryId: "vegetables", rating: 4.9, reviewCount: 310, description: "Flavourful garlic bulbs — the backbone of countless dishes. Each bulb is firm and fragrant, ideal for roasting, sautéing, or pressing.", tags: ["Antifungal", "Flavour Booster"], origin: "Spain", storage: "Store at room temperature in a dry place.", nutritionHighlights: ["Allicin", "Immunity Support", "Low Calorie"] },
  { id: "p9",  name: "Kale Bunch",                  price: 2.49, originalPrice: 3.49, onSale: true, unit: "1 bunch", emoji: "🥬", categoryId: "vegetables", rating: 4.7, reviewCount: 88, description: "Hearty curly kale — a superfood powerhouse. Blanch it, massage it raw, blend it into smoothies, or bake into crispy chips.", tags: ["Superfood", "Organic"], origin: "California, USA", storage: "Refrigerate. Use within 5–7 days.", nutritionHighlights: ["Vitamin K", "Iron", "Calcium"] },
  { id: "p10", name: "Sweet Potato 1kg",            price: 2.99, unit: "1kg",     emoji: "🍠", categoryId: "vegetables", rating: 4.8, reviewCount: 141, description: "Natural sweetness in every bite. Roast, mash, bake, or use in curries — sweet potatoes are as versatile as they are nutritious.", tags: ["High Fibre", "Naturally Sweet"], origin: "USA", storage: "Store in a cool dry place. Do not refrigerate.", nutritionHighlights: ["Beta-Carotene", "Fibre", "Potassium"] },

  // fruits
  { id: "p11", name: "Banana Bunch 6pk",            price: 1.99, unit: "6 pack",  emoji: "🍌", categoryId: "fruits", rating: 4.6, reviewCount: 287, description: "Perfectly ripe bananas — naturally sweet and creamy. A quick energy boost, great for smoothies, baking, and snacking any time of day.", tags: ["Energy Boost", "No Added Sugar"], origin: "Costa Rica", storage: "Keep at room temperature. Refrigerate to slow ripening.", nutritionHighlights: ["Potassium", "Vitamin B6", "Natural Energy"] },
  { id: "p12", name: "Strawberries 400g",           price: 4.49, originalPrice: 5.99, onSale: true, unit: "400g", emoji: "🍓", categoryId: "fruits", rating: 4.9, reviewCount: 352, description: "Plump, juicy strawberries picked at peak sweetness. Eat fresh, add to yogurt, blend into smoothies, or top your pavlova.", tags: ["Seasonal", "Sweet", "British Grown"], origin: "UK", storage: "Refrigerate. Consume within 2–3 days.", nutritionHighlights: ["Vitamin C", "Folate", "Antioxidants"] },
  { id: "p13", name: "Blueberries 150g",            price: 3.99, unit: "150g",    emoji: "🫐", categoryId: "fruits", rating: 4.8, reviewCount: 198, description: "Antioxidant-rich blueberries — small but mighty. Perfect straight from the punnet, over oats, or folded into baked goods.", tags: ["Antioxidant", "Superfood"], origin: "Chile", storage: "Refrigerate. Use within 5–7 days.", nutritionHighlights: ["Antioxidants", "Vitamin C", "Fibre"] },
  { id: "p14", name: "Avocado Ripe 2pk",            price: 3.49, unit: "2 pack",  emoji: "🥑", categoryId: "fruits", rating: 4.7, reviewCount: 423, description: "Perfectly ripe Hass avocados — creamy, buttery, and ready to eat today. Scoop onto toast, mash into guacamole, or slice into salads.", tags: ["Ripe & Ready", "Healthy Fats"], origin: "Mexico", storage: "Refrigerate once ripe. Use within 2 days.", nutritionHighlights: ["Healthy Fats", "Fibre", "Potassium"] },
  { id: "p15", name: "Mango Large",                 price: 2.49, unit: "1 each",  emoji: "🥭", categoryId: "fruits", rating: 4.6, reviewCount: 115, description: "Sweet and fragrant Alphonso-style mango — the king of tropical fruits. Eat fresh, blend into lassi, or dice into salsa.", tags: ["Tropical", "Vitamin A Rich"], origin: "India", storage: "Ripen at room temperature. Refrigerate when ripe.", nutritionHighlights: ["Vitamin A", "Vitamin C", "Folate"] },
  { id: "p16", name: "Green Grapes 500g",           price: 3.79, unit: "500g",    emoji: "🍇", categoryId: "fruits", rating: 4.5, reviewCount: 94, description: "Seedless green grapes — crisp, refreshing and naturally sweet. Snack as-is, freeze for a cool treat, or add to cheese boards.", tags: ["Seedless", "Refreshing"], origin: "South Africa", storage: "Refrigerate. Consume within 1 week.", nutritionHighlights: ["Vitamin K", "Resveratrol", "Hydrating"] },
  { id: "p17", name: "Watermelon Mini",             price: 5.99, unit: "1 each",  emoji: "🍉", categoryId: "fruits", rating: 4.8, reviewCount: 167, description: "Compact mini watermelon — perfectly sweet and hydrating. Ideal for smaller households. Slice and serve chilled on a hot day.", tags: ["Hydrating", "Seedless", "Summer"], origin: "Spain", storage: "Refrigerate after cutting. Consume within 3 days.", nutritionHighlights: ["Lycopene", "Hydrating", "Vitamin C"] },
  { id: "p18", name: "Pineapple Whole",             price: 3.99, originalPrice: 4.99, onSale: true, unit: "1 each", emoji: "🍍", categoryId: "fruits", rating: 4.6, reviewCount: 143, description: "Golden ripe whole pineapple — tangy, sweet, and loaded with bromelain. Grill it, blend it, or eat fresh. A tropical classic.", tags: ["Tropical", "Bromelain Rich"], origin: "Costa Rica", storage: "Store at room temp until ripe. Refrigerate once cut.", nutritionHighlights: ["Bromelain", "Vitamin C", "Manganese"] },

  // dairy
  { id: "p19", name: "Organic Whole Milk 1L",       price: 3.99, originalPrice: 4.99, onSale: true, unit: "1 bottle", emoji: "🥛", categoryId: "dairy", rating: 4.8, reviewCount: 267, description: "Rich, creamy organic whole milk from grass-fed cows. Minimally processed to preserve natural goodness. Perfect for drinking, cooking, or your morning latte.", tags: ["Organic", "Grass-Fed", "Full Fat"], origin: "UK", storage: "Refrigerate. Consume by best-before date.", nutritionHighlights: ["Calcium", "Protein", "Vitamin D"] },
  { id: "p20", name: "Free Range Eggs 12pk",        price: 5.49, unit: "12 pack", emoji: "🥚", categoryId: "dairy", rating: 4.9, reviewCount: 398, description: "Fresh free-range eggs from hens with access to outdoor pasture. Golden yolks, superior taste — perfect for every egg recipe you love.", tags: ["Free Range", "Welfare Assured"], origin: "UK", storage: "Refrigerate. Best before date on pack.", nutritionHighlights: ["Complete Protein", "Vitamin D", "Choline"] },
  { id: "p21", name: "Greek Yogurt Plain 500g",     price: 3.49, unit: "500g",    emoji: "🥣", categoryId: "dairy", rating: 4.7, reviewCount: 189, description: "Thick, tangy Greek-style yogurt strained to perfection. Enjoy with honey and berries, use in dips, or dollop onto curries.", tags: ["High Protein", "Probiotic"], origin: "Greece", storage: "Refrigerate. Consume within 3 days of opening.", nutritionHighlights: ["Protein", "Probiotics", "Calcium"] },
  { id: "p22", name: "Cheddar Cheese Block 400g",   price: 6.99, originalPrice: 8.49, onSale: true, unit: "400g", emoji: "🧀", categoryId: "dairy", rating: 4.8, reviewCount: 231, description: "Mature vintage cheddar — bold, sharp, and incredibly satisfying. Grate over pasta, melt into sauces, or serve on a cracker board.", tags: ["Mature", "Vintage", "Award Winning"], origin: "Somerset, UK", storage: "Refrigerate. Keep wrapped. Use within 3 weeks.", nutritionHighlights: ["Calcium", "Protein", "Vitamin B12"] },
  { id: "p23", name: "Butter Unsalted 250g",        price: 4.79, unit: "250g",    emoji: "🧈", categoryId: "dairy", rating: 4.7, reviewCount: 154, description: "Pure unsalted butter made from fresh cream. Ideal for baking, sautéing, and spreading. Rich, clean flavour — no additives.", tags: ["Pure", "Baking Grade"], origin: "Ireland", storage: "Refrigerate. Can freeze up to 3 months.", nutritionHighlights: ["Healthy Fats", "Vitamin A", "Vitamin D"] },
  { id: "p24", name: "Brie Cheese 200g",            price: 5.99, originalPrice: 7.49, onSale: true, unit: "200g", emoji: "🧀", categoryId: "dairy", rating: 4.6, reviewCount: 88, description: "Velvety, creamy Brie with a bloomy white rind. Serve at room temperature with fruit, jam, and crusty bread for an elegant spread.", tags: ["Soft Cheese", "French Style"], origin: "Normandy, France", storage: "Refrigerate. Remove from fridge 30 min before serving.", nutritionHighlights: ["Calcium", "Healthy Fats", "Vitamin B12"] },

  // drinks
  { id: "p25", name: "Orange Juice 1.75L",          price: 4.99, originalPrice: 6.29, onSale: true, unit: "1.75L", emoji: "🍊", categoryId: "drinks", rating: 4.7, reviewCount: 176, description: "Freshly squeezed orange juice — bright, tangy, and naturally sweet. No added sugar, no preservatives. Just pure sunshine in a bottle.", tags: ["No Added Sugar", "Fresh Squeezed"], origin: "Brazil", storage: "Refrigerate. Consume within 3 days of opening.", nutritionHighlights: ["Vitamin C", "Folate", "Potassium"] },
  { id: "p26", name: "Sparkling Water 6pk",         price: 3.79, unit: "6 pack",  emoji: "💧", categoryId: "drinks", rating: 4.5, reviewCount: 112, description: "Crisp, naturally carbonated mineral water. Zero calories, zero sugar. Refreshingly clean — the perfect everyday hydration choice.", tags: ["Zero Calorie", "Natural Minerals"], origin: "Italy", storage: "Store in a cool dry place.", nutritionHighlights: ["Zero Calories", "Natural Minerals", "Hydrating"] },
  { id: "p27", name: "Kombucha Ginger Lemon 330ml", price: 3.99, unit: "330ml",   emoji: "🧃", categoryId: "drinks", rating: 4.6, reviewCount: 143, description: "Raw, naturally fermented kombucha with zingy ginger and lemon. Live cultures for gut health. Low sugar, big flavour.", tags: ["Probiotic", "Live Cultures", "Low Sugar"], origin: "UK", storage: "Keep refrigerated. Shake gently before opening.", nutritionHighlights: ["Probiotics", "B Vitamins", "Low Sugar"] },
  { id: "p28", name: "Cold Brew Coffee 500ml",      price: 6.99, unit: "500ml",   emoji: "☕", categoryId: "drinks", rating: 4.8, reviewCount: 224, description: "Slow-steeped cold brew coffee — smooth, low-acid, and naturally sweet without bitterness. Serve over ice straight from the fridge.", tags: ["Cold Brew", "Low Acid", "Ready to Drink"], origin: "Colombia", storage: "Refrigerate. Consume within 7 days of opening.", nutritionHighlights: ["Natural Caffeine", "Antioxidants", "Low Acid"] },
  { id: "p29", name: "Coconut Water 1L",            price: 3.49, unit: "1L",      emoji: "🥥", categoryId: "drinks", rating: 4.7, reviewCount: 167, description: "Pure coconut water — nature's sports drink. Naturally isotonic, packed with electrolytes, and lightly sweet. No added sugar.", tags: ["Electrolytes", "No Added Sugar", "Natural"], origin: "Thailand", storage: "Store in a cool dry place. Refrigerate after opening.", nutritionHighlights: ["Electrolytes", "Potassium", "Natural Sugars"] },

  // grocery
  { id: "p30", name: "Basmati Rice 2kg",            price: 7.99, unit: "2kg",     emoji: "🍚", categoryId: "grocery", rating: 4.8, reviewCount: 312, description: "Premium aged Basmati rice — long-grain, fluffy, and fragrant. Each grain separates perfectly when cooked. The foundation of any great biryani or pilaf.", tags: ["Aged", "Extra Long Grain"], origin: "India", storage: "Store in a cool dry place in an airtight container.", nutritionHighlights: ["Low GI", "Gluten Free", "Complex Carbs"] },
  { id: "p31", name: "Pasta Penne 500g",            price: 2.29, unit: "500g",    emoji: "🍝", categoryId: "grocery", rating: 4.6, reviewCount: 145, description: "Classic bronze-die penne rigate — ridged tubes that hold sauce beautifully. Made from durum wheat semolina. Al dente in 11 minutes.", tags: ["Bronze Die", "Durum Wheat"], origin: "Italy", storage: "Store in a cool dry place.", nutritionHighlights: ["Complex Carbs", "Protein", "Iron"] },
  { id: "p32", name: "Tomato Passata 680ml",        price: 2.99, unit: "680ml",   emoji: "🍅", categoryId: "grocery", rating: 4.7, reviewCount: 198, description: "Smooth, strained tomato passata made from sun-ripened Italian plum tomatoes. The purest base for any pasta sauce, pizza, or stew.", tags: ["Passata", "No Additives", "Italian"], origin: "Italy", storage: "Store in a cool dry place. Refrigerate after opening.", nutritionHighlights: ["Lycopene", "Vitamin C", "Low Calorie"] },
  { id: "p33", name: "Extra Virgin Olive Oil 500ml",price: 8.99, unit: "500ml",   emoji: "🫙", categoryId: "grocery", rating: 4.9, reviewCount: 276, description: "First cold-pressed extra virgin olive oil from a single estate. Peppery finish, rich in polyphenols. Drizzle over everything.", tags: ["Cold Pressed", "Single Estate", "Award Winning"], origin: "Crete, Greece", storage: "Store in a cool dark place away from heat.", nutritionHighlights: ["Healthy Fats", "Polyphenols", "Vitamin E"] },
  { id: "p34", name: "Soy Sauce 250ml",             price: 2.29, unit: "250ml",   emoji: "🫙", categoryId: "grocery", rating: 4.7, reviewCount: 189, description: "Naturally brewed soy sauce — rich, umami, and deeply flavourful. Aged in traditional wooden barrels for a complex, balanced taste.", tags: ["Naturally Brewed", "Umami", "No Preservatives"], origin: "Japan", storage: "Store in a cool dry place. Refrigerate after opening.", nutritionHighlights: ["Umami", "Low Calorie", "Antioxidants"] },
  { id: "p35", name: "Canned Tuna 3pk",             price: 4.49, unit: "3 pack",  emoji: "🐟", categoryId: "grocery", rating: 4.6, reviewCount: 167, description: "Line-caught yellowfin tuna packed in spring water. Firm, flavourful, and high in protein. Dolphin-safe and sustainably sourced.", tags: ["Line Caught", "Sustainable", "High Protein"], origin: "Pacific Ocean", storage: "Store in a cool dry place. Refrigerate after opening.", nutritionHighlights: ["Protein", "Omega-3", "Selenium"] },
  { id: "p36", name: "Honey Raw 340g",              price: 6.99, unit: "340g",    emoji: "🍯", categoryId: "grocery", rating: 4.9, reviewCount: 342, description: "Unfiltered, unpasteurised raw honey — natural enzymes and pollen intact. Wildflower varieties with a rich floral aroma and depth of flavour.", tags: ["Raw", "Unfiltered", "Wildflower"], origin: "New Zealand", storage: "Store at room temperature. Never refrigerate.", nutritionHighlights: ["Antioxidants", "Enzymes", "Natural Sugars"] },

  // beef
  { id: "p37", name: "Minced Beef 500g",            price: 6.49, unit: "500g",    emoji: "🥩", categoryId: "beef", rating: 4.7, reviewCount: 203, description: "Lean 15% fat minced beef from grass-fed cattle. Versatile and flavourful — perfect for burgers, bolognese, meatballs, and tacos.", tags: ["Grass-Fed", "15% Fat", "British"], origin: "UK", storage: "Refrigerate. Use by date on pack. Freeze on day of purchase.", nutritionHighlights: ["Protein", "Iron", "Zinc", "B12"] },
  { id: "p38", name: "Ribeye Steak 300g",           price: 12.99, originalPrice: 15.99, onSale: true, unit: "300g", emoji: "🥩", categoryId: "beef", rating: 4.9, reviewCount: 287, description: "28-day dry-aged ribeye from Red Angus cattle. Intense marbling delivers unmatched flavour and tenderness. The king of steaks.", tags: ["Dry Aged", "Red Angus", "Prime Cut"], origin: "UK", storage: "Refrigerate. Cook within 2 days or freeze.", nutritionHighlights: ["Protein", "Iron", "Zinc", "Omega-3"] },
  { id: "p39", name: "Beef Sirloin 400g",           price: 9.99, unit: "400g",    emoji: "🥩", categoryId: "beef", rating: 4.8, reviewCount: 156, description: "Premium sirloin with perfect fat coverage for self-basting. Tender, lean, and deeply flavourful. Pan-sear to a golden crust in minutes.", tags: ["Sirloin", "Lean", "Prime Cut"], origin: "UK", storage: "Refrigerate. Cook within 2 days or freeze.", nutritionHighlights: ["Protein", "Iron", "B12"] },

  // chicken
  { id: "p40", name: "Chicken Breast",              price: 5.00, priceMax: 12.00, unit: "1 each", emoji: "🍗", categoryId: "chicken", hasVariants: true, rating: 4.6, reviewCount: 312, description: "Premium free-range chicken breast — lean, tender, and versatile. Available in various sizes. Ideal for grilling, baking, stir-fries, or meal prep.", tags: ["Free Range", "Lean", "High Protein"], origin: "UK", storage: "Refrigerate. Use within 2 days or freeze.", nutritionHighlights: ["Protein", "Low Fat", "B Vitamins"] },
  { id: "p41", name: "Chicken Thighs 600g",         price: 5.49, unit: "600g",    emoji: "🍗", categoryId: "chicken", rating: 4.8, reviewCount: 224, description: "Juicy bone-in chicken thighs — more flavourful than breast, forgiving to cook. Roast, braise, or marinate for weekend family dinners.", tags: ["Bone-In", "Juicy", "Free Range"], origin: "UK", storage: "Refrigerate. Use within 2 days or freeze.", nutritionHighlights: ["Protein", "Iron", "Zinc"] },
  { id: "p42", name: "Whole Chicken 1.5kg",         price: 8.99, originalPrice: 10.99, onSale: true, unit: "1.5kg", emoji: "🍗", categoryId: "chicken", rating: 4.9, reviewCount: 198, description: "Whole free-range chicken — perfect for Sunday roasts, poaching, or spatchcocking on the BBQ. Excellent value with endless leftovers.", tags: ["Free Range", "Welfare Assured", "Whole Bird"], origin: "UK", storage: "Refrigerate. Use within 2 days or freeze.", nutritionHighlights: ["Protein", "B Vitamins", "Selenium"] },

  // fish
  { id: "p43", name: "Atlantic Salmon Fillet 400g", price: 9.99, unit: "400g",    emoji: "🐟", categoryId: "fish", rating: 4.8, reviewCount: 243, description: "Fresh Scottish Atlantic salmon fillet — rich in omega-3, silky, and naturally pink. Bake, pan-fry, or poach in under 15 minutes.", tags: ["Scottish", "Rich Omega-3", "Sustainable"], origin: "Scotland", storage: "Refrigerate. Cook within 2 days. Can freeze.", nutritionHighlights: ["Omega-3", "Protein", "Vitamin D", "B12"] },
  { id: "p44", name: "Cod Fillet 300g",             price: 7.49, originalPrice: 8.99, onSale: true, unit: "300g", emoji: "🐟", categoryId: "fish", rating: 4.7, reviewCount: 178, description: "Firm, flaky, and mild MSC-certified cod fillet. A household staple — batter it, bake it, or steam with herbs. Sustainably caught.", tags: ["MSC Certified", "Sustainable", "Mild Flavour"], origin: "North Atlantic", storage: "Refrigerate. Cook within 2 days. Can freeze.", nutritionHighlights: ["Protein", "Low Fat", "B Vitamins"] },
  { id: "p45", name: "Tiger Prawns 400g",           price: 11.99, unit: "400g",   emoji: "🦐", categoryId: "fish", rating: 4.7, reviewCount: 134, description: "Jumbo raw tiger prawns, shell-on for maximum flavour. Marinate and grill, sauté with garlic butter, or toss into paella or curry.", tags: ["Raw", "Jumbo", "Shell-On"], origin: "Thailand", storage: "Keep frozen. Defrost in fridge overnight before use.", nutritionHighlights: ["Protein", "Low Fat", "Selenium", "Iodine"] },

  // snacks
  { id: "p46", name: "Dark Chocolate 85% 100g",     price: 2.99, unit: "100g",    emoji: "🍫", categoryId: "snacks", rating: 4.8, reviewCount: 367, description: "Intensely dark 85% cocoa chocolate — complex, bittersweet, and deeply satisfying. One square is all you need. Rich in antioxidants.", tags: ["85% Cocoa", "Vegan", "Fair Trade"], origin: "Ecuador", storage: "Store in a cool dry place below 20°C.", nutritionHighlights: ["Antioxidants", "Iron", "Magnesium"] },
  { id: "p47", name: "Peanut Butter Smooth 400g",   price: 4.29, unit: "400g",    emoji: "🥜", categoryId: "snacks", rating: 4.7, reviewCount: 289, description: "100% roasted peanuts — nothing else. Smooth, creamy, and naturally delicious. No palm oil, no added sugar. Stir and enjoy.", tags: ["No Added Sugar", "No Palm Oil", "100% Peanut"], origin: "USA", storage: "Store in a cool dry place. Refrigerate after opening.", nutritionHighlights: ["Protein", "Healthy Fats", "Vitamin E"] },
  { id: "p48", name: "Granola Oat & Honey 500g",    price: 4.99, originalPrice: 6.49, onSale: true, unit: "500g", emoji: "🥣", categoryId: "snacks", rating: 4.8, reviewCount: 213, description: "Golden baked granola with rolled oats, honey, and toasted seeds. Perfectly crunchy. Serve with yogurt, milk, or eat by the handful.", tags: ["Baked", "No Artificial Flavours", "High Fibre"], origin: "UK", storage: "Store in an airtight container.", nutritionHighlights: ["Fibre", "Whole Grains", "Natural Sugars"] },
  { id: "p49", name: "Mixed Berry Jam 370g",        price: 3.99, unit: "370g",    emoji: "🫐", categoryId: "snacks", rating: 4.6, reviewCount: 124, description: "Artisan mixed berry preserve — strawberries, raspberries, and blueberries slow-cooked to perfection. Spread generously on warm toast.", tags: ["Artisan", "No Artificial Colours", "High Fruit"], origin: "France", storage: "Store in a cool dry place. Refrigerate after opening.", nutritionHighlights: ["Vitamin C", "Antioxidants", "No Preservatives"] },
  { id: "p50", name: "Hummus Classic 250g",         price: 3.49, unit: "250g",    emoji: "🫘", categoryId: "snacks", rating: 4.7, reviewCount: 198, description: "Smooth, silky hummus made from Lebanese chickpeas with authentic tahini and a drizzle of olive oil. Perfect for dipping or spreading.", tags: ["Plant-Based", "High Protein", "No Preservatives"], origin: "Lebanon", storage: "Refrigerate. Consume within 5 days of opening.", nutritionHighlights: ["Protein", "Fibre", "Healthy Fats"] },

  // diet
  { id: "p51", name: "Oat Milk Barista 1L",         price: 4.49, originalPrice: 5.49, onSale: true, unit: "1L", emoji: "🥛", categoryId: "diet", rating: 4.7, reviewCount: 312, description: "Barista-edition oat milk that froths beautifully and steams like dairy. Subtle sweetness, creamy body. The top choice for plant-based lattes.", tags: ["Barista Edition", "Froths Well", "Plant-Based"], origin: "Sweden", storage: "Store at room temp. Refrigerate after opening. Use within 5 days.", nutritionHighlights: ["Fibre", "Low Saturated Fat", "Vitamin D"] },
  { id: "p52", name: "Plant-Based Burger Patties 2pk", price: 7.99, unit: "2 pack", emoji: "🍔", categoryId: "diet", rating: 4.5, reviewCount: 167, description: "Juicy plant-based burger patties that sizzle, sear, and satisfy like the real thing. Made from pea protein with a smoky beetroot finish.", tags: ["Vegan", "High Protein", "Pea Protein"], origin: "UK", storage: "Refrigerate. Use by date on pack. Can freeze.", nutritionHighlights: ["Protein", "Iron", "Low Saturated Fat"] },
  { id: "p53", name: "Cauliflower Pizza Base",      price: 6.49, originalPrice: 7.99, onSale: true, unit: "1 each", emoji: "🍕", categoryId: "diet", rating: 4.4, reviewCount: 143, description: "Low-carb cauliflower pizza base — crispy, light, and gluten-free. Top with your favourite sauce and toppings for a guilt-free pizza night.", tags: ["Gluten Free", "Low Carb", "Cauliflower"], origin: "UK", storage: "Keep frozen. Cook from frozen.", nutritionHighlights: ["Low Carb", "Gluten Free", "High Fibre"] },
  { id: "p54", name: "Chickpea Pasta 400g",         price: 3.99, unit: "400g",    emoji: "🍝", categoryId: "diet", rating: 4.6, reviewCount: 198, description: "High-protein chickpea pasta — same satisfying texture as wheat pasta but with 2x the protein and 3x the fibre. Gluten-free and delicious.", tags: ["Gluten Free", "High Protein", "High Fibre"], origin: "Italy", storage: "Store in a cool dry place.", nutritionHighlights: ["Protein", "Fibre", "Gluten Free"] },
  { id: "p55", name: "Vegan Cheese Shreds",         price: 4.00, priceMax: 8.00, unit: "1 each", emoji: "🧀", categoryId: "diet", hasVariants: true, rating: 4.3, reviewCount: 87, description: "Melty, stretchy vegan cheese shreds — available in cheddar and mozzarella styles. Made from coconut oil and cashews. Great on pizza and pasta.", tags: ["Vegan", "Dairy Free", "Melts Well"], origin: "UK", storage: "Refrigerate. Use within 5 days of opening.", nutritionHighlights: ["Dairy Free", "Vegan", "Calcium Fortified"] },

  // nutrition
  { id: "p56", name: "Spirulina Powder 200g",       price: 9.99, unit: "200g",    emoji: "🌿", categoryId: "nutrition", rating: 4.6, reviewCount: 134, description: "Certified organic spirulina powder — one of the world's most nutrient-dense foods. Add a teaspoon to smoothies or juices for a daily superfood boost.", tags: ["Organic", "Superfood", "Vegan"], origin: "USA", storage: "Store in a cool dry place away from light.", nutritionHighlights: ["Complete Protein", "Iron", "B12", "Chlorophyll"] },
  { id: "p57", name: "Pea Protein Powder 500g",     price: 19.99, unit: "500g",   emoji: "💪", categoryId: "nutrition", rating: 4.7, reviewCount: 267, description: "Clean, unflavoured pea protein isolate — 80% protein per serving. Mixes smoothly into shakes and recipes. No artificial sweeteners.", tags: ["80% Protein", "Unflavoured", "Vegan"], origin: "France", storage: "Store in a cool dry place. Keep sealed.", nutritionHighlights: ["High Protein", "BCAA Rich", "Low Fat"] },
  { id: "p58", name: "Hemp Seeds 250g",             price: 7.49, unit: "250g",    emoji: "🌿", categoryId: "nutrition", rating: 4.7, reviewCount: 156, description: "Hulled hemp seeds — a complete protein with all essential amino acids and an ideal omega-3 to omega-6 ratio. Sprinkle on anything.", tags: ["Complete Protein", "Omega-3", "Vegan"], origin: "Canada", storage: "Refrigerate after opening to preserve freshness.", nutritionHighlights: ["Complete Protein", "Omega-3", "Omega-6"] },

  // healthy
  { id: "p59", name: "Quinoa Tri-Colour 500g",      price: 5.79, unit: "500g",    emoji: "🌾", categoryId: "healthy", rating: 4.8, reviewCount: 223, description: "A beautiful blend of white, red, and black quinoa — fluffy, nutty, and complete with all 9 essential amino acids. Cook like rice in 15 minutes.", tags: ["Gluten Free", "Complete Protein", "Organic"], origin: "Bolivia", storage: "Store in an airtight container in a cool dry place.", nutritionHighlights: ["Complete Protein", "Gluten Free", "Iron"] },
  { id: "p60", name: "Matcha Latte Powder 100g",    price: 12.99, unit: "100g",   emoji: "🍵", categoryId: "healthy", rating: 4.7, reviewCount: 189, description: "Ceremonial-grade Japanese matcha powder — vibrant green, smooth, and naturally sweet. Whisk with oat milk for a calming daily ritual.", tags: ["Ceremonial Grade", "Japanese", "L-Theanine"], origin: "Uji, Japan", storage: "Store in an airtight tin away from light and moisture.", nutritionHighlights: ["L-Theanine", "Antioxidants", "Natural Caffeine"] },
  { id: "p61", name: "Kimchi Traditional 400g",     price: 5.99, unit: "400g",    emoji: "🥬", categoryId: "healthy", rating: 4.6, reviewCount: 143, description: "Authentically fermented Korean kimchi — spicy, tangy, and alive with beneficial bacteria. Add to rice bowls, tacos, and eggs for instant depth.", tags: ["Fermented", "Probiotic", "Traditional Recipe"], origin: "South Korea", storage: "Refrigerate at all times. Keeps for several months.", nutritionHighlights: ["Probiotics", "Vitamin C", "Fibre"] },
  { id: "p62", name: "Tempeh Original 200g",        price: 3.99, unit: "200g",    emoji: "🫘", categoryId: "healthy", rating: 4.5, reviewCount: 97, description: "Firm, nutty Indonesian-style tempeh — fermented soybean cake with a meaty texture. Slice and fry, crumble into bowls, or marinate and grill.", tags: ["Fermented", "Probiotic", "High Protein"], origin: "Indonesia", storage: "Refrigerate. Use within 5 days. Can freeze.", nutritionHighlights: ["Protein", "Probiotics", "Iron"] },

  // breakfast
  { id: "p63", name: "Sourdough Bread Loaf",        price: 4.29, originalPrice: 5.50, onSale: true, unit: "1 loaf", emoji: "🍞", categoryId: "breakfast", rating: 4.9, reviewCount: 412, description: "Slow-fermented sourdough loaf with a crackly crust and chewy, open crumb. Made using a 72-hour starter fermentation. No added yeast.", tags: ["72hr Fermentation", "Artisan", "No Additives"], origin: "UK", storage: "Store at room temperature. Best within 3 days. Freeze for longer.", nutritionHighlights: ["Low GI", "Gut Friendly", "Natural Fermentation"] },
  { id: "p64", name: "Almond Butter 250g",          price: 8.99, unit: "250g",    emoji: "🥜", categoryId: "breakfast", rating: 4.8, reviewCount: 267, description: "Creamy roasted almond butter — 100% almonds, nothing added. Smooth, rich, and satisfying on toast, in oats, or straight off the spoon.", tags: ["100% Almond", "No Sugar", "No Palm Oil"], origin: "California, USA", storage: "Store in a cool dry place. Refrigerate after opening.", nutritionHighlights: ["Vitamin E", "Healthy Fats", "Protein"] },
  { id: "p65", name: "Date Syrup 330g",             price: 6.49, originalPrice: 8.49, onSale: true, unit: "330g", emoji: "🍯", categoryId: "breakfast", rating: 4.7, reviewCount: 156, description: "Pure Medjool date syrup — a natural sweetener with a rich caramel depth. Drizzle on pancakes, stir into oatmeal, or use as a honey substitute.", tags: ["100% Dates", "Natural Sweetener", "High Iron"], origin: "Middle East", storage: "Store in a cool dry place.", nutritionHighlights: ["Iron", "Potassium", "Natural Sugars"] },

  // fastfood
  { id: "p66", name: "Frozen Pizza Margherita",     price: 5.99, unit: "1 each",  emoji: "🍕", categoryId: "fastfood", rating: 4.5, reviewCount: 189, description: "Stone-baked thin crust margherita pizza — tangy tomato, melty mozzarella, and fresh basil leaves. Ready in 12 minutes from frozen.", tags: ["Stone Baked", "Thin Crust", "Vegetarian"], origin: "Italy", storage: "Keep frozen. Cook from frozen.", nutritionHighlights: ["Calcium", "Protein", "Lycopene"] },
  { id: "p67", name: "Chicken Nuggets 500g",        price: 4.99, originalPrice: 6.49, onSale: true, unit: "500g", emoji: "🍗", categoryId: "fastfood", rating: 4.6, reviewCount: 223, description: "Crispy, golden chicken nuggets made from 100% chicken breast meat. Oven-ready in 15 minutes — the crowd-pleasing family favourite.", tags: ["100% Breast Meat", "Oven Ready", "No Artificial Colours"], origin: "UK", storage: "Keep frozen. Cook from frozen.", nutritionHighlights: ["Protein", "Low Fat", "No Artificial Additives"] },
  { id: "p68", name: "Fish Fingers 10pk",           price: 3.99, unit: "10 pack", emoji: "🐟", categoryId: "fastfood", rating: 4.6, reviewCount: 198, description: "Classic crispy fish fingers made from 100% cod fillet in a golden breadcrumb coating. MSC certified sustainable. An absolute teatime legend.", tags: ["MSC Certified", "Cod", "Sustainable"], origin: "Iceland", storage: "Keep frozen. Cook from frozen.", nutritionHighlights: ["Protein", "Omega-3", "Low Saturated Fat"] },

  // greens
  { id: "p69", name: "Organic Rocket 80g",          price: 3.49, unit: "80g",     emoji: "🥬", categoryId: "greens", rating: 4.7, reviewCount: 87, description: "Peppery, wild-style rocket leaves with a distinctive mustardy bite. Organic, pre-washed, and ready to dress. Elevates any salad instantly.", tags: ["Organic", "Pre-Washed", "Peppery"], origin: "Italy", storage: "Refrigerate. Use within 3 days of opening.", nutritionHighlights: ["Vitamin K", "Folate", "Calcium"] },
  { id: "p70", name: "Iceberg Lettuce",             price: 1.79, unit: "1 each",  emoji: "🥬", categoryId: "greens", rating: 4.4, reviewCount: 56, description: "Crisp, cool iceberg lettuce — satisfyingly crunchy with a mild, refreshing taste. Perfect for BLTs, tacos, and layered salads.", tags: ["Crunchy", "Hydrating", "Classic"], origin: "Spain", storage: "Refrigerate. Use within 5 days.", nutritionHighlights: ["Hydrating", "Low Calorie", "Vitamin K"] },
  { id: "p71", name: "Green Beans 300g",            price: 2.79, originalPrice: 3.29, onSale: true, unit: "300g", emoji: "🫛", categoryId: "greens", rating: 4.6, reviewCount: 112, description: "Tender fine green beans, trimmed and ready to cook. Blanch for 3 minutes, then toss in butter. A versatile and elegant side dish.", tags: ["Fine Beans", "Ready Trimmed", "Versatile"], origin: "Kenya", storage: "Refrigerate. Use within 3 days.", nutritionHighlights: ["Vitamin C", "Vitamin K", "Folate"] },

  // vitamins
  { id: "p72", name: "Açaí Frozen Puree 100g",     price: 3.49, unit: "100g",    emoji: "🍇", categoryId: "vitamins", rating: 4.7, reviewCount: 123, description: "Authentic Amazonian açaí berry puree — frozen at source to lock in nutrients. Blend into smoothie bowls, protein shakes, or desserts.", tags: ["Amazonian", "Antioxidant", "Frozen Fresh"], origin: "Brazil", storage: "Keep frozen. Use within 24hr of defrosting.", nutritionHighlights: ["Antioxidants", "Healthy Fats", "Fibre"] },
  { id: "p73", name: "Coconut Yogurt 400g",         price: 5.29, originalPrice: 6.99, onSale: true, unit: "400g", emoji: "🥥", categoryId: "vitamins", rating: 4.6, reviewCount: 143, description: "Thick, creamy coconut milk yogurt — naturally dairy-free and probiotic-rich. Lightly tangy, gorgeous with mango and granola.", tags: ["Dairy Free", "Probiotic", "Vegan"], origin: "UK", storage: "Refrigerate. Consume within 3 days of opening.", nutritionHighlights: ["Probiotics", "Dairy Free", "MCT Fats"] },
  { id: "p74", name: "Kefir Plain 750ml",           price: 4.99, unit: "750ml",   emoji: "🥛", categoryId: "vitamins", rating: 4.7, reviewCount: 167, description: "Traditional milk kefir — tangy, thin-drinking yogurt fermented with live kefir grains. Billions of live cultures per serving. Outstanding for gut health.", tags: ["Probiotic", "Live Cultures", "Traditional"], origin: "UK", storage: "Refrigerate. Consume within 5 days of opening.", nutritionHighlights: ["Probiotics", "Calcium", "Complete Protein"] },
];

export function getProductById(id: string): StoreProduct | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}

export function getRelatedProducts(categoryId: string, excludeId: string, limit = 6): StoreProduct[] {
  return ALL_PRODUCTS.filter((p) => p.categoryId === categoryId && p.id !== excludeId).slice(0, limit);
}

export function getCategoryLabel(categoryId: string): string {
  return CATEGORIES.find((c) => c.id === categoryId)?.label ?? categoryId;
}
